### ISSUE TITLE
command-line version of INSaFLU interest?

### ISSUE THREAD

**Issue by rpetit3** [INSaFLU/INSaFLU#27]
Hi INSaFLU Team!

Me again, I'm curious if there's interest in extracting INSaFLU into a workflow manager such as Nextflow for users to execute on the command-line. I'd like to be able to give it a go on our HPC system. 

I saw https://github.com/INSaFLU/docker for running the complete INSaFLU web-app in an off-line mode. Our HPC is SLURM and unfortunately docker-compose isn't going to be possible. 

I'd be willing to do much of the writing and push it back your way (e.g. something like `INSaFLU/INSaFLU-nf`). Or if you'd rather it stay unofficial that's ok too.

Cheers,
Robert

**Comment by dsobral** [comment]
Hello both,

We have planned for some time to develop a command-line version of INSaFLU, but never had the chance to really do it.

We do have a student developing a prototype in snakemake but it may take some time to have it in production.

Please feel free to develop one in WDL and/or Nextflow. We'll provide as much support as we can.

Best,
Daniel

**Comment by rpetit3** [comment]
Thank you @dsobral. Would you like this to remain unofficial or something to push back to INSaFLU?

**Comment by rpetit3** [comment]
Going to close for now since its likely to take a while. Cheers
